### ISSUE TITLE
Bugfix: Actualizar el "user_info.user_quota_used_percentage", viene siempre en 0.

### ISSUE THREAD

**Issue by martindonofrio** [martineq/tp7552#139]
el metodo: get_user_info devuelve el "user_info", pero siempre con el campo "user_quota_used_percentage" en cero.
Si no es un dato que sea necesario persistir, ya que se puede calcular, como ya viene  en esta estructura, por "prolijidad" deberia venir calculado.

Se esta considerando la foto de perfil como quota usada?.

**Comment by martineq** [comment]
@martindonofrio: La foto de perfil no cuenta en la cuota del usuario, sólo los archivos que se encuentran en las carpetas.

**Comment by martineq** [comment]
Se confirma que el user_info.user_quota_used_percentage no devuelve `0`, sino la cuota usada. Sólo devuelve el valor cero si no existen archivos subidos y en ese caso lo realiza con un formato decimal.-
