### ISSUE TITLE
Feature: El metodo log_in debe devolver el "quotaAvailable" del usuario.

### ISSUE THREAD

**Issue by martindonofrio** [martineq/tp7552#140]
cambiar el metodo: log_in(email, password, new_token, userId, status))

para poder completar el quotaAvailable.

{
    "userId": 1
    "email": "rcortazzo@....",
    "token": "xxx211d",
    "quotaAvailable": "XXXX"
}

**Comment by martineq** [comment]
"quotaAvailable" agregado en el método.-
