### ISSUE TITLE
bugfix: Al salir de la vista de visualizacion del perfil de usuario.

### ISSUE THREAD

**Issue by martindonofrio** [martineq/tp7552#141]
Si salgo con el boton de "atras" del celu, anda de 10, pero si uso la flechita que esta arriba a la izquierda " que es de la app", se muere.

**Comment by e-liva** [comment]
Solved. 
La flecha de navegación no correspondía que estuviera para mantener la coherencia con el resto de las Activities. 
Solo se vuelve ahora con el botón back.
