### ISSUE TITLE
Validar estructura xxx@xxx.x en E-mail

### ISSUE THREAD

**Issue by e-liva** [martineq/tp7552#153]

**Comment by martineq** [comment]
@e-liva Pego un par de datos por si sirve:

**1)** [Official java email package](http://www.oracle.com/technetwork/java/javamail/index.html)
```java
public static boolean isValidEmailAddress(String email) {
   boolean result = true;
   try {
      InternetAddress emailAddr = new InternetAddress(email);
      emailAddr.validate();
   } catch (AddressException ex) {
      result = false;
   }
   return result;
}
```
----------------
**2)** [How to validate email address with regular expression](http://www.mkyong.com/regular-expressions/how-to-validate-email-address-with-regular-expression/)
