### ISSUE TITLE
Papelera sólo muestra el último archivo borrado

### ISSUE THREAD

**Issue by romicorty** [martineq/tp7552#162]
Flujo para reproducir el error:

1) Cargo más de un archivo en una carpeta
2) Elimino uno
3) Voy a papelera y se ve ok
4) Borro el otro
5) Voy a papelera y sólo veo el último archivo borrado

Comportamiento esperado:

Se tienen que ver en papelera todos los archivos eliminados

**Comment by martineq** [comment]
Me parece que es un error mío, me lo asigno y te aviso.-

**Comment by martineq** [comment]
Fixed.-
