### ISSUE TITLE
Agregarme como Owner del repo

### ISSUE THREAD

**Issue by martindonofrio** [martineq/tp7552#17]
Mart, como no soy el owner del proyecto no lo puedo integrar con Travis. Me haces owner?

**Comment by martineq** [comment]
GitHub no me deja agregar varios owners. SI querés decime los pasos así lo vinculo y así después podés agregar el YAML.

**Comment by martineq** [comment]
Ya quedó vinculado Travis CI al repositorio, solo falta agregar el `.travis.yml` en el raíz y hacer un primer `push`.
