### ISSUE TITLE
Not found! Servicio de owners y todos los search

### ISSUE THREAD

**Issue by e-liva** [martineq/tp7552#173]

**Comment by martindonofrio** [comment]
Se probo y esta funcional.
Considerar

1- Chequer que la uri sea la del documento.
2- NO se buscan carpetas, solo files

Ejemplo de curl, de busqueda de files, andando.
curl -X GET -H "Authorization:f5fb4811d4745ae2d29e2a39b2762798" http://localhost:8080/info/users/1/file?name=IMG
