### ISSUE TITLE
El servicio "TRAE LOS USUARIOS QUE CUMPLEN CONSULTA" devuelve error 

### ISSUE THREAD

**Issue by romicorty** [martineq/tp7552#174]
---> HTTP GET http://190.7.56.249:8055/user/1/users?q=nah
11-18 02:55:18.191  20873-21181/com.fiuba.app.udrive D/Retrofit﹕ Accept: application/json
11-18 02:55:18.191  20873-21181/com.fiuba.app.udrive D/Retrofit﹕ Authorization: 632f0ad5e18e9c8082a6bb6374683633
11-18 02:55:18.191  20873-21181/com.fiuba.app.udrive D/Retrofit﹕ ---> END HTTP (no body)
11-18 02:55:18.235  20873-21181/com.fiuba.app.udrive D/Retrofit﹕ <--- HTTP 401 http://190.7.56.249:8055/user/1/users?q=nah (40ms)
11-18 02:55:18.235  20873-21181/com.fiuba.app.udrive D/Retrofit﹕ Content-Type: application/json
11-18 02:55:18.235  20873-21181/com.fiuba.app.udrive D/Retrofit﹕ Transfer-Encoding: chunked
11-18 02:55:18.235  20873-21181/com.fiuba.app.udrive D/Retrofit﹕ OkHttp-Selected-Protocol: http/1.1
11-18 02:55:18.235  20873-21181/com.fiuba.app.udrive D/Retrofit﹕ <--- END HTTP (2-byte body)
11-18 02:55:18.243  20873-20873/com.fiuba.app.udrive E/SearchUsersActivity﹕ Authentication error

**Comment by martindonofrio** [comment]
habia que limpiar la base para que arranque...
